// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC08IznndGqh6MuruzeT-z9ezyGVnyWJBM',
    appId: '1:307468264353:web:9f517346a054be357ae1e0',
    messagingSenderId: '307468264353',
    projectId: 'alfred-ebe8a',
    authDomain: 'alfred-ebe8a.firebaseapp.com',
    storageBucket: 'alfred-ebe8a.firebasestorage.app',
    measurementId: 'G-SS7S2LRQ5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJHjunOUdUp00f1qbqdCNtsDWDf090S0',
    appId: '1:307468264353:android:11ce8ce1a7f373127ae1e0',
    messagingSenderId: '307468264353',
    projectId: 'alfred-ebe8a',
    storageBucket: 'alfred-ebe8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGuEOstXI9pBqVWBQsRbQN167geNU_eR4',
    appId: '1:307468264353:ios:d16fc2186e04c54a7ae1e0',
    messagingSenderId: '307468264353',
    projectId: 'alfred-ebe8a',
    storageBucket: 'alfred-ebe8a.firebasestorage.app',
    iosClientId: '307468264353-7qcjemeuv8bm84upel8kes5sjl2po84l.apps.googleusercontent.com',
    iosBundleId: 'com.example.alfredApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGuEOstXI9pBqVWBQsRbQN167geNU_eR4',
    appId: '1:307468264353:ios:d16fc2186e04c54a7ae1e0',
    messagingSenderId: '307468264353',
    projectId: 'alfred-ebe8a',
    storageBucket: 'alfred-ebe8a.firebasestorage.app',
    iosClientId: '307468264353-7qcjemeuv8bm84upel8kes5sjl2po84l.apps.googleusercontent.com',
    iosBundleId: 'com.example.alfredApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC08IznndGqh6MuruzeT-z9ezyGVnyWJBM',
    appId: '1:307468264353:web:c0d09d48dd214a917ae1e0',
    messagingSenderId: '307468264353',
    projectId: 'alfred-ebe8a',
    authDomain: 'alfred-ebe8a.firebaseapp.com',
    storageBucket: 'alfred-ebe8a.firebasestorage.app',
    measurementId: 'G-DE34H9QX3S',
  );

}